# Generated by Django 3.2.6 on 2021-08-18 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='funcao',
        ),
    ]
