# Generated by Django 3.2.6 on 2021-08-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcao',
            name='funcao',
            field=models.CharField(max_length=50, verbose_name='Função'),
        ),
    ]
