# Generated by Django 3.2.6 on 2021-09-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0002_alter_funcao_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcao',
            name='funcao',
            field=models.CharField(max_length=50, unique=True, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ministério'),
        ),
    ]
