# Generated by Django 3.2.6 on 2021-08-18 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ministerio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=50, verbose_name='Evento')),
                ('ultima_alteracao', models.DateTimeField(auto_now=True, verbose_name='Ultima Alteração')),
                ('observacao', models.TextField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('observacao', models.TextField(blank=True, max_length=1000, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escala.evento', verbose_name='Evento')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ministerio.funcao', verbose_name='Função')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Responsavel')),
            ],
        ),
    ]
