# Generated by Django 3.2.6 on 2021-08-18 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0002_alter_funcao_funcao'),
        ('escala', '0002_auto_20210818_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='funcao',
        ),
        migrations.AddField(
            model_name='escala',
            name='funcao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ministerio.funcao', verbose_name='Função'),
            preserve_default=False,
        ),
    ]
