# Generated by Django 3.2.6 on 2021-09-10 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0002_alter_funcao_funcao'),
        ('escala', '0004_auto_20210910_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escala.evento', unique=True, verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ministerio.funcao', unique=True, verbose_name='Função'),
        ),
    ]
