# Generated by Django 3.2.6 on 2021-09-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0006_auto_20210910_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='nome_evento',
            field=models.CharField(max_length=50, unique=True, verbose_name='Evento'),
        ),
    ]
