# Generated by Django 3.2.6 on 2021-09-10 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0007_alter_evento_nome_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 9, 10, 11, 26, 32, 841006)),
        ),
    ]
