# Generated by Django 3.2.6 on 2021-10-04 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0008_alter_escala_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 10, 4, 18, 59, 57, 526230)),
        ),
    ]
