# Generated by Django 3.2.6 on 2021-10-19 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0012_alter_escala_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 10, 19, 10, 58, 59, 204806)),
        ),
    ]
