# Generated by Django 3.2.6 on 2021-10-19 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0013_alter_escala_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinhaEscala',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Minha Escala',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('escala.escala',),
        ),
        migrations.AlterField(
            model_name='escala',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 10, 19, 14, 41, 34, 592750)),
        ),
    ]
