# Generated by Django 3.2.6 on 2021-10-19 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0014_auto_20211019_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escala',
            options={'verbose_name': 'Escala Geral', 'verbose_name_plural': 'Escala Geral'},
        ),
        migrations.AlterField(
            model_name='escala',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 10, 19, 14, 47, 39, 637121)),
        ),
    ]
